# Generated by Django 3.2.9 on 2021-12-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='sp_id',
            field=models.CharField(default='_', max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='sp_id',
            field=models.CharField(default='_', max_length=200),
        ),
    ]
